# Generated by Django 4.2.3 on 2023-08-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_user_follows_newpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.JSONField(default=list),
        ),
    ]
