# Generated by Django 4.2.3 on 2023-08-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_user_followers_alter_user_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follows',
            new_name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.JSONField(default=list),
        ),
    ]
