# Generated by Django 4.2.3 on 2023-08-29 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_follows_user_followers_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 21, 29, 0, 226090)),
        ),
    ]
