# Generated by Django 4.2.3 on 2023-08-29 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_newpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 19, 31, 14, 965729, tzinfo=datetime.timezone.utc)),
        ),
    ]
