# Generated by Django 4.2.3 on 2023-08-31 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_newpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 10, 9, 8, 64506, tzinfo=datetime.timezone.utc)),
        ),
    ]
