# Generated by Django 4.2.3 on 2023-08-31 10:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_newpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 10, 22, 57, 743887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_liked', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='network.newpost')),
            ],
        ),
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.ManyToManyField(through='network.Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
