# Generated by Django 4.2.3 on 2023-08-31 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_newpost_likes_alter_newpost_timestamp_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 10, 24, 48, 12099, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('liked_by', 'post')},
        ),
    ]
